Added "lain.ux"-style check for existance of M1_ROOT environment variable before proceeding.

diff --git a/tools/bin/build_xst b/tools/bin/build_xst
--- a/tools/bin/build_xst
+++ b/tools/bin/build_xst
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+if [ -z "$M1_ROOT" ]; then echo "***ERROR***: M1_ROOT variable is undefined, please set it and run 'source sourceme'."; exit 1; fi
+if ! [ -d "$M1_ROOT" ]; then echo "***ERROR***: directory '$M1_ROOT' does not exist, please check it and run 'source sourceme' again."; exit 1; fi
+
 rm -rf $M1_ROOT/run/synth/xst
 mkdir $M1_ROOT/run/synth/xst
 cd $M1_ROOT/run/synth/xst
